#ifndef SIXTRACKLIB_COMMON_BE_TRICUB_COEFFICIENTS_C99_H__
#define SIXTRACKLIB_COMMON_BE_TRICUB_COEFFICIENTS_C99_H__

/*
#if !defined(SIXTRL_NO_SYSTEM_INCLUDES)
    #include <stddef.h>
    #include <math.h>
#endif */
/* !defined(SIXTRL_NO_SYSTEM_INCLUDES) */

#if !defined(SIXTRL_NO_INCLUDES)
    #include "sixtracklib/common/definitions.h"
    #include "sixtracklib/common/be_tricub/be_tricub.h"
#endif /* !defined(SIXTRL_NO_INCLUDES) */

#if !defined( _GPUCODE ) && defined( __cplusplus )
extern "C" {
#endif /* !defined( _GPUCODE ) && defined( __cplusplus ) */

SIXTRL_STATIC SIXTRL_FN void NS(tricub_construct_coefs)(
    SIXTRL_BUFFER_DATAPTR_DEC const NS(TriCubData) *const SIXTRL_RESTRICT tricub_data,
    NS(be_tricub_int_t) const ix,
    NS(be_tricub_int_t) const iy,
    NS(be_tricub_int_t) const iz,
    SIXTRL_ARGPTR_DEC NS(be_tricub_real_t)* coefs);

#if !defined( _GPUCODE ) && defined( __cplusplus )
}
#endif /* !defined( _GPUCODE ) && defined( __cplusplus ) */

/* ************************************************************************* */
/* ************************************************************************* */

#if !defined( _GPUCODE ) && defined( __cplusplus )
extern "C" {
#endif /* !defined( _GPUCODE ) && defined( __cplusplus ) */

SIXTRL_INLINE void NS(tricub_construct_coefs)(
    SIXTRL_BUFFER_DATAPTR_DEC const NS(TriCubData) *const SIXTRL_RESTRICT tricub_data,
    NS(be_tricub_int_t) const ix,
    NS(be_tricub_int_t) const iy,
    NS(be_tricub_int_t) const iz,
    SIXTRL_ARGPTR_DEC NS(be_tricub_real_t)* coefs)
{

    SIXTRL_BUFFER_DATAPTR_DEC NS(be_tricub_real_t) const* LUT = 
        NS(TriCubData_const_table_begin)( tricub_data );

    NS(be_tricub_int_t) const nx = NS(TriCubData_nx)( tricub_data );
    NS(be_tricub_int_t) const ny = NS(TriCubData_ny)( tricub_data );


    NS(be_tricub_real_t) const tri_consts[9] = 
        {2.0, 3.0, 4.0, 6.0, 8.0, 9.0, 12.0, 18.0, 27.0};

    NS(be_tricub_real_t) b_val;
    NS(be_tricub_int_t) ii;

    ii =  8 * ( (ix  ) + nx * ( (iy  ) + ny * (iz  ) ) );
    b_val = LUT[ii];
    coefs[0] = b_val;
    coefs[2] = -(tri_consts[1] * b_val);
    coefs[3] = tri_consts[0] * b_val;
    coefs[8] = -(tri_consts[1] * b_val);
    coefs[10] = tri_consts[5] * b_val;
    coefs[11] = -(tri_consts[3] * b_val);
    coefs[12] = tri_consts[0] * b_val;
    coefs[14] = -(tri_consts[3] * b_val);
    coefs[15] = tri_consts[2] * b_val;
    coefs[32] = -(tri_consts[1] * b_val);
    coefs[34] = tri_consts[5] * b_val;
    coefs[35] = -(tri_consts[3] * b_val);
    coefs[40] = tri_consts[5] * b_val;
    coefs[42] = -(tri_consts[8] * b_val);
    coefs[43] = tri_consts[7] * b_val;
    coefs[44] = -(tri_consts[3] * b_val);
    coefs[46] = tri_consts[7] * b_val;
    coefs[47] = -(tri_consts[6] * b_val);
    coefs[48] = tri_consts[0] * b_val;
    coefs[50] = -(tri_consts[3] * b_val);
    coefs[51] = tri_consts[2] * b_val;
    coefs[56] = -(tri_consts[3] * b_val);
    coefs[58] = tri_consts[7] * b_val;
    coefs[59] = -(tri_consts[6] * b_val);
    coefs[60] = tri_consts[2] * b_val;
    coefs[62] = -(tri_consts[6] * b_val);
    coefs[63] = tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[1] = b_val;
    coefs[2] -= tri_consts[0] * b_val;
    coefs[3] += b_val;
    coefs[9] = -(tri_consts[1] * b_val);
    coefs[10] += tri_consts[3] * b_val;
    coefs[11] -= tri_consts[1] * b_val;
    coefs[13] = tri_consts[0] * b_val;
    coefs[14] -= tri_consts[2] * b_val;
    coefs[15] += tri_consts[0] * b_val;
    coefs[33] = -(tri_consts[1] * b_val);
    coefs[34] += tri_consts[3] * b_val;
    coefs[35] -= tri_consts[1] * b_val;
    coefs[41] = tri_consts[5] * b_val;
    coefs[42] -= tri_consts[7] * b_val;
    coefs[43] += tri_consts[5] * b_val;
    coefs[45] = -(tri_consts[3] * b_val);
    coefs[46] += tri_consts[6] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[49] = tri_consts[0] * b_val;
    coefs[50] -= tri_consts[2] * b_val;
    coefs[51] += tri_consts[0] * b_val;
    coefs[57] = -(tri_consts[3] * b_val);
    coefs[58] += tri_consts[6] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[61] = tri_consts[2] * b_val;
    coefs[62] -= tri_consts[4] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[4] = b_val;
    coefs[6] = -(tri_consts[1] * b_val);
    coefs[7] = tri_consts[0] * b_val;
    coefs[8] -= tri_consts[0] * b_val;
    coefs[10] += tri_consts[3] * b_val;
    coefs[11] -= tri_consts[2] * b_val;
    coefs[12] += b_val;
    coefs[14] -= tri_consts[1] * b_val;
    coefs[15] += tri_consts[0] * b_val;
    coefs[36] = -(tri_consts[1] * b_val);
    coefs[38] = tri_consts[5] * b_val;
    coefs[39] = -(tri_consts[3] * b_val);
    coefs[40] += tri_consts[3] * b_val;
    coefs[42] -= tri_consts[7] * b_val;
    coefs[43] += tri_consts[6] * b_val;
    coefs[44] -= tri_consts[1] * b_val;
    coefs[46] += tri_consts[5] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[52] = tri_consts[0] * b_val;
    coefs[54] = -(tri_consts[3] * b_val);
    coefs[55] = tri_consts[2] * b_val;
    coefs[56] -= tri_consts[2] * b_val;
    coefs[58] += tri_consts[6] * b_val;
    coefs[59] -= tri_consts[4] * b_val;
    coefs[60] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[16] = b_val;
    coefs[18] = -(tri_consts[1] * b_val);
    coefs[19] = tri_consts[0] * b_val;
    coefs[24] = -(tri_consts[1] * b_val);
    coefs[26] = tri_consts[5] * b_val;
    coefs[27] = -(tri_consts[3] * b_val);
    coefs[28] = tri_consts[0] * b_val;
    coefs[30] = -(tri_consts[3] * b_val);
    coefs[31] = tri_consts[2] * b_val;
    coefs[32] -= tri_consts[0] * b_val;
    coefs[34] += tri_consts[3] * b_val;
    coefs[35] -= tri_consts[2] * b_val;
    coefs[40] += tri_consts[3] * b_val;
    coefs[42] -= tri_consts[7] * b_val;
    coefs[43] += tri_consts[6] * b_val;
    coefs[44] -= tri_consts[2] * b_val;
    coefs[46] += tri_consts[6] * b_val;
    coefs[47] -= tri_consts[4] * b_val;
    coefs[48] += b_val;
    coefs[50] -= tri_consts[1] * b_val;
    coefs[51] += tri_consts[0] * b_val;
    coefs[56] -= tri_consts[1] * b_val;
    coefs[58] += tri_consts[5] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[60] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[5] = b_val;
    coefs[6] -= tri_consts[0] * b_val;
    coefs[7] += b_val;
    coefs[9] -= tri_consts[0] * b_val;
    coefs[10] += tri_consts[2] * b_val;
    coefs[11] -= tri_consts[0] * b_val;
    coefs[13] += b_val;
    coefs[14] -= tri_consts[0] * b_val;
    coefs[15] += b_val;
    coefs[37] = -(tri_consts[1] * b_val);
    coefs[38] += tri_consts[3] * b_val;
    coefs[39] -= tri_consts[1] * b_val;
    coefs[41] += tri_consts[3] * b_val;
    coefs[42] -= tri_consts[6] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[45] -= tri_consts[1] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[1] * b_val;
    coefs[53] = tri_consts[0] * b_val;
    coefs[54] -= tri_consts[2] * b_val;
    coefs[55] += tri_consts[0] * b_val;
    coefs[57] -= tri_consts[2] * b_val;
    coefs[58] += tri_consts[4] * b_val;
    coefs[59] -= tri_consts[2] * b_val;
    coefs[61] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[2] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[17] = b_val;
    coefs[18] -= tri_consts[0] * b_val;
    coefs[19] += b_val;
    coefs[25] = -(tri_consts[1] * b_val);
    coefs[26] += tri_consts[3] * b_val;
    coefs[27] -= tri_consts[1] * b_val;
    coefs[29] = tri_consts[0] * b_val;
    coefs[30] -= tri_consts[2] * b_val;
    coefs[31] += tri_consts[0] * b_val;
    coefs[33] -= tri_consts[0] * b_val;
    coefs[34] += tri_consts[2] * b_val;
    coefs[35] -= tri_consts[0] * b_val;
    coefs[41] += tri_consts[3] * b_val;
    coefs[42] -= tri_consts[6] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[45] -= tri_consts[2] * b_val;
    coefs[46] += tri_consts[4] * b_val;
    coefs[47] -= tri_consts[2] * b_val;
    coefs[49] += b_val;
    coefs[50] -= tri_consts[0] * b_val;
    coefs[51] += b_val;
    coefs[57] -= tri_consts[1] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[1] * b_val;
    coefs[61] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[2] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[20] = b_val;
    coefs[22] = -(tri_consts[1] * b_val);
    coefs[23] = tri_consts[0] * b_val;
    coefs[24] -= tri_consts[0] * b_val;
    coefs[26] += tri_consts[3] * b_val;
    coefs[27] -= tri_consts[2] * b_val;
    coefs[28] += b_val;
    coefs[30] -= tri_consts[1] * b_val;
    coefs[31] += tri_consts[0] * b_val;
    coefs[36] -= tri_consts[0] * b_val;
    coefs[38] += tri_consts[3] * b_val;
    coefs[39] -= tri_consts[2] * b_val;
    coefs[40] += tri_consts[2] * b_val;
    coefs[42] -= tri_consts[6] * b_val;
    coefs[43] += tri_consts[4] * b_val;
    coefs[44] -= tri_consts[0] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[2] * b_val;
    coefs[52] += b_val;
    coefs[54] -= tri_consts[1] * b_val;
    coefs[55] += tri_consts[0] * b_val;
    coefs[56] -= tri_consts[0] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[2] * b_val;
    coefs[60] += b_val;
    coefs[62] -= tri_consts[1] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[21] = b_val;
    coefs[22] -= tri_consts[0] * b_val;
    coefs[23] += b_val;
    coefs[25] -= tri_consts[0] * b_val;
    coefs[26] += tri_consts[2] * b_val;
    coefs[27] -= tri_consts[0] * b_val;
    coefs[29] += b_val;
    coefs[30] -= tri_consts[0] * b_val;
    coefs[31] += b_val;
    coefs[37] -= tri_consts[0] * b_val;
    coefs[38] += tri_consts[2] * b_val;
    coefs[39] -= tri_consts[0] * b_val;
    coefs[41] += tri_consts[2] * b_val;
    coefs[42] -= tri_consts[4] * b_val;
    coefs[43] += tri_consts[2] * b_val;
    coefs[45] -= tri_consts[0] * b_val;
    coefs[46] += tri_consts[2] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[53] += b_val;
    coefs[54] -= tri_consts[0] * b_val;
    coefs[55] += b_val;
    coefs[57] -= tri_consts[0] * b_val;
    coefs[58] += tri_consts[2] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[61] += b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += b_val;
    ii =  8 * ( (ix+1) + nx * ( (iy  ) + ny * (iz  ) ) );
    b_val = LUT[ii];
    coefs[2] += tri_consts[1] * b_val;
    coefs[3] -= tri_consts[0] * b_val;
    coefs[10] -= tri_consts[5] * b_val;
    coefs[11] += tri_consts[3] * b_val;
    coefs[14] += tri_consts[3] * b_val;
    coefs[15] -= tri_consts[2] * b_val;
    coefs[34] -= tri_consts[5] * b_val;
    coefs[35] += tri_consts[3] * b_val;
    coefs[42] += tri_consts[8] * b_val;
    coefs[43] -= tri_consts[7] * b_val;
    coefs[46] -= tri_consts[7] * b_val;
    coefs[47] += tri_consts[6] * b_val;
    coefs[50] += tri_consts[3] * b_val;
    coefs[51] -= tri_consts[2] * b_val;
    coefs[58] -= tri_consts[7] * b_val;
    coefs[59] += tri_consts[6] * b_val;
    coefs[62] += tri_consts[6] * b_val;
    coefs[63] -= tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[2] -= b_val;
    coefs[3] += b_val;
    coefs[10] += tri_consts[1] * b_val;
    coefs[11] -= tri_consts[1] * b_val;
    coefs[14] -= tri_consts[0] * b_val;
    coefs[15] += tri_consts[0] * b_val;
    coefs[34] += tri_consts[1] * b_val;
    coefs[35] -= tri_consts[1] * b_val;
    coefs[42] -= tri_consts[5] * b_val;
    coefs[43] += tri_consts[5] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[50] -= tri_consts[0] * b_val;
    coefs[51] += tri_consts[0] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[62] -= tri_consts[2] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[6] += tri_consts[1] * b_val;
    coefs[7] -= tri_consts[0] * b_val;
    coefs[10] -= tri_consts[3] * b_val;
    coefs[11] += tri_consts[2] * b_val;
    coefs[14] += tri_consts[1] * b_val;
    coefs[15] -= tri_consts[0] * b_val;
    coefs[38] -= tri_consts[5] * b_val;
    coefs[39] += tri_consts[3] * b_val;
    coefs[42] += tri_consts[7] * b_val;
    coefs[43] -= tri_consts[6] * b_val;
    coefs[46] -= tri_consts[5] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[54] += tri_consts[3] * b_val;
    coefs[55] -= tri_consts[2] * b_val;
    coefs[58] -= tri_consts[6] * b_val;
    coefs[59] += tri_consts[4] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[18] += tri_consts[1] * b_val;
    coefs[19] -= tri_consts[0] * b_val;
    coefs[26] -= tri_consts[5] * b_val;
    coefs[27] += tri_consts[3] * b_val;
    coefs[30] += tri_consts[3] * b_val;
    coefs[31] -= tri_consts[2] * b_val;
    coefs[34] -= tri_consts[3] * b_val;
    coefs[35] += tri_consts[2] * b_val;
    coefs[42] += tri_consts[7] * b_val;
    coefs[43] -= tri_consts[6] * b_val;
    coefs[46] -= tri_consts[6] * b_val;
    coefs[47] += tri_consts[4] * b_val;
    coefs[50] += tri_consts[1] * b_val;
    coefs[51] -= tri_consts[0] * b_val;
    coefs[58] -= tri_consts[5] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[6] -= b_val;
    coefs[7] += b_val;
    coefs[10] += tri_consts[0] * b_val;
    coefs[11] -= tri_consts[0] * b_val;
    coefs[14] -= b_val;
    coefs[15] += b_val;
    coefs[38] += tri_consts[1] * b_val;
    coefs[39] -= tri_consts[1] * b_val;
    coefs[42] -= tri_consts[3] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[46] += tri_consts[1] * b_val;
    coefs[47] -= tri_consts[1] * b_val;
    coefs[54] -= tri_consts[0] * b_val;
    coefs[55] += tri_consts[0] * b_val;
    coefs[58] += tri_consts[2] * b_val;
    coefs[59] -= tri_consts[2] * b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[18] -= b_val;
    coefs[19] += b_val;
    coefs[26] += tri_consts[1] * b_val;
    coefs[27] -= tri_consts[1] * b_val;
    coefs[30] -= tri_consts[0] * b_val;
    coefs[31] += tri_consts[0] * b_val;
    coefs[34] += tri_consts[0] * b_val;
    coefs[35] -= tri_consts[0] * b_val;
    coefs[42] -= tri_consts[3] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[46] += tri_consts[2] * b_val;
    coefs[47] -= tri_consts[2] * b_val;
    coefs[50] -= b_val;
    coefs[51] += b_val;
    coefs[58] += tri_consts[1] * b_val;
    coefs[59] -= tri_consts[1] * b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[22] += tri_consts[1] * b_val;
    coefs[23] -= tri_consts[0] * b_val;
    coefs[26] -= tri_consts[3] * b_val;
    coefs[27] += tri_consts[2] * b_val;
    coefs[30] += tri_consts[1] * b_val;
    coefs[31] -= tri_consts[0] * b_val;
    coefs[38] -= tri_consts[3] * b_val;
    coefs[39] += tri_consts[2] * b_val;
    coefs[42] += tri_consts[6] * b_val;
    coefs[43] -= tri_consts[4] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[2] * b_val;
    coefs[54] += tri_consts[1] * b_val;
    coefs[55] -= tri_consts[0] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[2] * b_val;
    coefs[62] += tri_consts[1] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[22] -= b_val;
    coefs[23] += b_val;
    coefs[26] += tri_consts[0] * b_val;
    coefs[27] -= tri_consts[0] * b_val;
    coefs[30] -= b_val;
    coefs[31] += b_val;
    coefs[38] += tri_consts[0] * b_val;
    coefs[39] -= tri_consts[0] * b_val;
    coefs[42] -= tri_consts[2] * b_val;
    coefs[43] += tri_consts[2] * b_val;
    coefs[46] += tri_consts[0] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[54] -= b_val;
    coefs[55] += b_val;
    coefs[58] += tri_consts[0] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[62] -= b_val;
    coefs[63] += b_val;
    ii =  8 * ( (ix  ) + nx * ( (iy+1) + ny * (iz  ) ) );
    b_val = LUT[ii];
    coefs[8] += tri_consts[1] * b_val;
    coefs[10] -= tri_consts[5] * b_val;
    coefs[11] += tri_consts[3] * b_val;
    coefs[12] -= tri_consts[0] * b_val;
    coefs[14] += tri_consts[3] * b_val;
    coefs[15] -= tri_consts[2] * b_val;
    coefs[40] -= tri_consts[5] * b_val;
    coefs[42] += tri_consts[8] * b_val;
    coefs[43] -= tri_consts[7] * b_val;
    coefs[44] += tri_consts[3] * b_val;
    coefs[46] -= tri_consts[7] * b_val;
    coefs[47] += tri_consts[6] * b_val;
    coefs[56] += tri_consts[3] * b_val;
    coefs[58] -= tri_consts[7] * b_val;
    coefs[59] += tri_consts[6] * b_val;
    coefs[60] -= tri_consts[2] * b_val;
    coefs[62] += tri_consts[6] * b_val;
    coefs[63] -= tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[9] += tri_consts[1] * b_val;
    coefs[10] -= tri_consts[3] * b_val;
    coefs[11] += tri_consts[1] * b_val;
    coefs[13] -= tri_consts[0] * b_val;
    coefs[14] += tri_consts[2] * b_val;
    coefs[15] -= tri_consts[0] * b_val;
    coefs[41] -= tri_consts[5] * b_val;
    coefs[42] += tri_consts[7] * b_val;
    coefs[43] -= tri_consts[5] * b_val;
    coefs[45] += tri_consts[3] * b_val;
    coefs[46] -= tri_consts[6] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[57] += tri_consts[3] * b_val;
    coefs[58] -= tri_consts[6] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[61] -= tri_consts[2] * b_val;
    coefs[62] += tri_consts[4] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[8] -= b_val;
    coefs[10] += tri_consts[1] * b_val;
    coefs[11] -= tri_consts[0] * b_val;
    coefs[12] += b_val;
    coefs[14] -= tri_consts[1] * b_val;
    coefs[15] += tri_consts[0] * b_val;
    coefs[40] += tri_consts[1] * b_val;
    coefs[42] -= tri_consts[5] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[44] -= tri_consts[1] * b_val;
    coefs[46] += tri_consts[5] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[56] -= tri_consts[0] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[2] * b_val;
    coefs[60] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[24] += tri_consts[1] * b_val;
    coefs[26] -= tri_consts[5] * b_val;
    coefs[27] += tri_consts[3] * b_val;
    coefs[28] -= tri_consts[0] * b_val;
    coefs[30] += tri_consts[3] * b_val;
    coefs[31] -= tri_consts[2] * b_val;
    coefs[40] -= tri_consts[3] * b_val;
    coefs[42] += tri_consts[7] * b_val;
    coefs[43] -= tri_consts[6] * b_val;
    coefs[44] += tri_consts[2] * b_val;
    coefs[46] -= tri_consts[6] * b_val;
    coefs[47] += tri_consts[4] * b_val;
    coefs[56] += tri_consts[1] * b_val;
    coefs[58] -= tri_consts[5] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[60] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[9] -= b_val;
    coefs[10] += tri_consts[0] * b_val;
    coefs[11] -= b_val;
    coefs[13] += b_val;
    coefs[14] -= tri_consts[0] * b_val;
    coefs[15] += b_val;
    coefs[41] += tri_consts[1] * b_val;
    coefs[42] -= tri_consts[3] * b_val;
    coefs[43] += tri_consts[1] * b_val;
    coefs[45] -= tri_consts[1] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[1] * b_val;
    coefs[57] -= tri_consts[0] * b_val;
    coefs[58] += tri_consts[2] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[61] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[2] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[25] += tri_consts[1] * b_val;
    coefs[26] -= tri_consts[3] * b_val;
    coefs[27] += tri_consts[1] * b_val;
    coefs[29] -= tri_consts[0] * b_val;
    coefs[30] += tri_consts[2] * b_val;
    coefs[31] -= tri_consts[0] * b_val;
    coefs[41] -= tri_consts[3] * b_val;
    coefs[42] += tri_consts[6] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[45] += tri_consts[2] * b_val;
    coefs[46] -= tri_consts[4] * b_val;
    coefs[47] += tri_consts[2] * b_val;
    coefs[57] += tri_consts[1] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[1] * b_val;
    coefs[61] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[2] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[24] -= b_val;
    coefs[26] += tri_consts[1] * b_val;
    coefs[27] -= tri_consts[0] * b_val;
    coefs[28] += b_val;
    coefs[30] -= tri_consts[1] * b_val;
    coefs[31] += tri_consts[0] * b_val;
    coefs[40] += tri_consts[0] * b_val;
    coefs[42] -= tri_consts[3] * b_val;
    coefs[43] += tri_consts[2] * b_val;
    coefs[44] -= tri_consts[0] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[2] * b_val;
    coefs[56] -= b_val;
    coefs[58] += tri_consts[1] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[60] += b_val;
    coefs[62] -= tri_consts[1] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[25] -= b_val;
    coefs[26] += tri_consts[0] * b_val;
    coefs[27] -= b_val;
    coefs[29] += b_val;
    coefs[30] -= tri_consts[0] * b_val;
    coefs[31] += b_val;
    coefs[41] += tri_consts[0] * b_val;
    coefs[42] -= tri_consts[2] * b_val;
    coefs[43] += tri_consts[0] * b_val;
    coefs[45] -= tri_consts[0] * b_val;
    coefs[46] += tri_consts[2] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[57] -= b_val;
    coefs[58] += tri_consts[0] * b_val;
    coefs[59] -= b_val;
    coefs[61] += b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += b_val;
    ii =  8 * ( (ix+1) + nx * ( (iy+1) + ny * (iz  ) ) );
    b_val = LUT[ii];
    coefs[10] += tri_consts[5] * b_val;
    coefs[11] -= tri_consts[3] * b_val;
    coefs[14] -= tri_consts[3] * b_val;
    coefs[15] += tri_consts[2] * b_val;
    coefs[42] -= tri_consts[8] * b_val;
    coefs[43] += tri_consts[7] * b_val;
    coefs[46] += tri_consts[7] * b_val;
    coefs[47] -= tri_consts[6] * b_val;
    coefs[58] += tri_consts[7] * b_val;
    coefs[59] -= tri_consts[6] * b_val;
    coefs[62] -= tri_consts[6] * b_val;
    coefs[63] += tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[10] -= tri_consts[1] * b_val;
    coefs[11] += tri_consts[1] * b_val;
    coefs[14] += tri_consts[0] * b_val;
    coefs[15] -= tri_consts[0] * b_val;
    coefs[42] += tri_consts[5] * b_val;
    coefs[43] -= tri_consts[5] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[62] += tri_consts[2] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[10] -= tri_consts[1] * b_val;
    coefs[11] += tri_consts[0] * b_val;
    coefs[14] += tri_consts[1] * b_val;
    coefs[15] -= tri_consts[0] * b_val;
    coefs[42] += tri_consts[5] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[46] -= tri_consts[5] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[2] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[26] += tri_consts[5] * b_val;
    coefs[27] -= tri_consts[3] * b_val;
    coefs[30] -= tri_consts[3] * b_val;
    coefs[31] += tri_consts[2] * b_val;
    coefs[42] -= tri_consts[7] * b_val;
    coefs[43] += tri_consts[6] * b_val;
    coefs[46] += tri_consts[6] * b_val;
    coefs[47] -= tri_consts[4] * b_val;
    coefs[58] += tri_consts[5] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[10] += b_val;
    coefs[11] -= b_val;
    coefs[14] -= b_val;
    coefs[15] += b_val;
    coefs[42] -= tri_consts[1] * b_val;
    coefs[43] += tri_consts[1] * b_val;
    coefs[46] += tri_consts[1] * b_val;
    coefs[47] -= tri_consts[1] * b_val;
    coefs[58] += tri_consts[0] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[26] -= tri_consts[1] * b_val;
    coefs[27] += tri_consts[1] * b_val;
    coefs[30] += tri_consts[0] * b_val;
    coefs[31] -= tri_consts[0] * b_val;
    coefs[42] += tri_consts[3] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[46] -= tri_consts[2] * b_val;
    coefs[47] += tri_consts[2] * b_val;
    coefs[58] -= tri_consts[1] * b_val;
    coefs[59] += tri_consts[1] * b_val;
    coefs[62] += tri_consts[0] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[26] -= tri_consts[1] * b_val;
    coefs[27] += tri_consts[0] * b_val;
    coefs[30] += tri_consts[1] * b_val;
    coefs[31] -= tri_consts[0] * b_val;
    coefs[42] += tri_consts[3] * b_val;
    coefs[43] -= tri_consts[2] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[2] * b_val;
    coefs[58] -= tri_consts[1] * b_val;
    coefs[59] += tri_consts[0] * b_val;
    coefs[62] += tri_consts[1] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[26] += b_val;
    coefs[27] -= b_val;
    coefs[30] -= b_val;
    coefs[31] += b_val;
    coefs[42] -= tri_consts[0] * b_val;
    coefs[43] += tri_consts[0] * b_val;
    coefs[46] += tri_consts[0] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[58] += b_val;
    coefs[59] -= b_val;
    coefs[62] -= b_val;
    coefs[63] += b_val;
    ii =  8 * ( (ix  ) + nx * ( (iy  ) + ny * (iz+1) ) );
    b_val = LUT[ii];
    coefs[32] += tri_consts[1] * b_val;
    coefs[34] -= tri_consts[5] * b_val;
    coefs[35] += tri_consts[3] * b_val;
    coefs[40] -= tri_consts[5] * b_val;
    coefs[42] += tri_consts[8] * b_val;
    coefs[43] -= tri_consts[7] * b_val;
    coefs[44] += tri_consts[3] * b_val;
    coefs[46] -= tri_consts[7] * b_val;
    coefs[47] += tri_consts[6] * b_val;
    coefs[48] -= tri_consts[0] * b_val;
    coefs[50] += tri_consts[3] * b_val;
    coefs[51] -= tri_consts[2] * b_val;
    coefs[56] += tri_consts[3] * b_val;
    coefs[58] -= tri_consts[7] * b_val;
    coefs[59] += tri_consts[6] * b_val;
    coefs[60] -= tri_consts[2] * b_val;
    coefs[62] += tri_consts[6] * b_val;
    coefs[63] -= tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[33] += tri_consts[1] * b_val;
    coefs[34] -= tri_consts[3] * b_val;
    coefs[35] += tri_consts[1] * b_val;
    coefs[41] -= tri_consts[5] * b_val;
    coefs[42] += tri_consts[7] * b_val;
    coefs[43] -= tri_consts[5] * b_val;
    coefs[45] += tri_consts[3] * b_val;
    coefs[46] -= tri_consts[6] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[49] -= tri_consts[0] * b_val;
    coefs[50] += tri_consts[2] * b_val;
    coefs[51] -= tri_consts[0] * b_val;
    coefs[57] += tri_consts[3] * b_val;
    coefs[58] -= tri_consts[6] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[61] -= tri_consts[2] * b_val;
    coefs[62] += tri_consts[4] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[36] += tri_consts[1] * b_val;
    coefs[38] -= tri_consts[5] * b_val;
    coefs[39] += tri_consts[3] * b_val;
    coefs[40] -= tri_consts[3] * b_val;
    coefs[42] += tri_consts[7] * b_val;
    coefs[43] -= tri_consts[6] * b_val;
    coefs[44] += tri_consts[1] * b_val;
    coefs[46] -= tri_consts[5] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[52] -= tri_consts[0] * b_val;
    coefs[54] += tri_consts[3] * b_val;
    coefs[55] -= tri_consts[2] * b_val;
    coefs[56] += tri_consts[2] * b_val;
    coefs[58] -= tri_consts[6] * b_val;
    coefs[59] += tri_consts[4] * b_val;
    coefs[60] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[32] -= b_val;
    coefs[34] += tri_consts[1] * b_val;
    coefs[35] -= tri_consts[0] * b_val;
    coefs[40] += tri_consts[1] * b_val;
    coefs[42] -= tri_consts[5] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[44] -= tri_consts[0] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[2] * b_val;
    coefs[48] += b_val;
    coefs[50] -= tri_consts[1] * b_val;
    coefs[51] += tri_consts[0] * b_val;
    coefs[56] -= tri_consts[1] * b_val;
    coefs[58] += tri_consts[5] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[60] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[37] += tri_consts[1] * b_val;
    coefs[38] -= tri_consts[3] * b_val;
    coefs[39] += tri_consts[1] * b_val;
    coefs[41] -= tri_consts[3] * b_val;
    coefs[42] += tri_consts[6] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[45] += tri_consts[1] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[1] * b_val;
    coefs[53] -= tri_consts[0] * b_val;
    coefs[54] += tri_consts[2] * b_val;
    coefs[55] -= tri_consts[0] * b_val;
    coefs[57] += tri_consts[2] * b_val;
    coefs[58] -= tri_consts[4] * b_val;
    coefs[59] += tri_consts[2] * b_val;
    coefs[61] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[2] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[33] -= b_val;
    coefs[34] += tri_consts[0] * b_val;
    coefs[35] -= b_val;
    coefs[41] += tri_consts[1] * b_val;
    coefs[42] -= tri_consts[3] * b_val;
    coefs[43] += tri_consts[1] * b_val;
    coefs[45] -= tri_consts[0] * b_val;
    coefs[46] += tri_consts[2] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[49] += b_val;
    coefs[50] -= tri_consts[0] * b_val;
    coefs[51] += b_val;
    coefs[57] -= tri_consts[1] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[1] * b_val;
    coefs[61] += tri_consts[0] * b_val;
    coefs[62] -= tri_consts[2] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[36] -= b_val;
    coefs[38] += tri_consts[1] * b_val;
    coefs[39] -= tri_consts[0] * b_val;
    coefs[40] += tri_consts[0] * b_val;
    coefs[42] -= tri_consts[3] * b_val;
    coefs[43] += tri_consts[2] * b_val;
    coefs[44] -= b_val;
    coefs[46] += tri_consts[1] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[52] += b_val;
    coefs[54] -= tri_consts[1] * b_val;
    coefs[55] += tri_consts[0] * b_val;
    coefs[56] -= tri_consts[0] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[2] * b_val;
    coefs[60] += b_val;
    coefs[62] -= tri_consts[1] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[37] -= b_val;
    coefs[38] += tri_consts[0] * b_val;
    coefs[39] -= b_val;
    coefs[41] += tri_consts[0] * b_val;
    coefs[42] -= tri_consts[2] * b_val;
    coefs[43] += tri_consts[0] * b_val;
    coefs[45] -= b_val;
    coefs[46] += tri_consts[0] * b_val;
    coefs[47] -= b_val;
    coefs[53] += b_val;
    coefs[54] -= tri_consts[0] * b_val;
    coefs[55] += b_val;
    coefs[57] -= tri_consts[0] * b_val;
    coefs[58] += tri_consts[2] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[61] += b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += b_val;
    ii =  8 * ( (ix+1) + nx * ( (iy  ) + ny * (iz+1) ) );
    b_val = LUT[ii];
    coefs[34] += tri_consts[5] * b_val;
    coefs[35] -= tri_consts[3] * b_val;
    coefs[42] -= tri_consts[8] * b_val;
    coefs[43] += tri_consts[7] * b_val;
    coefs[46] += tri_consts[7] * b_val;
    coefs[47] -= tri_consts[6] * b_val;
    coefs[50] -= tri_consts[3] * b_val;
    coefs[51] += tri_consts[2] * b_val;
    coefs[58] += tri_consts[7] * b_val;
    coefs[59] -= tri_consts[6] * b_val;
    coefs[62] -= tri_consts[6] * b_val;
    coefs[63] += tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[34] -= tri_consts[1] * b_val;
    coefs[35] += tri_consts[1] * b_val;
    coefs[42] += tri_consts[5] * b_val;
    coefs[43] -= tri_consts[5] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[50] += tri_consts[0] * b_val;
    coefs[51] -= tri_consts[0] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[62] += tri_consts[2] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[38] += tri_consts[5] * b_val;
    coefs[39] -= tri_consts[3] * b_val;
    coefs[42] -= tri_consts[7] * b_val;
    coefs[43] += tri_consts[6] * b_val;
    coefs[46] += tri_consts[5] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[54] -= tri_consts[3] * b_val;
    coefs[55] += tri_consts[2] * b_val;
    coefs[58] += tri_consts[6] * b_val;
    coefs[59] -= tri_consts[4] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[34] -= tri_consts[1] * b_val;
    coefs[35] += tri_consts[0] * b_val;
    coefs[42] += tri_consts[5] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[2] * b_val;
    coefs[50] += tri_consts[1] * b_val;
    coefs[51] -= tri_consts[0] * b_val;
    coefs[58] -= tri_consts[5] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[38] -= tri_consts[1] * b_val;
    coefs[39] += tri_consts[1] * b_val;
    coefs[42] += tri_consts[3] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[46] -= tri_consts[1] * b_val;
    coefs[47] += tri_consts[1] * b_val;
    coefs[54] += tri_consts[0] * b_val;
    coefs[55] -= tri_consts[0] * b_val;
    coefs[58] -= tri_consts[2] * b_val;
    coefs[59] += tri_consts[2] * b_val;
    coefs[62] += tri_consts[0] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[34] += b_val;
    coefs[35] -= b_val;
    coefs[42] -= tri_consts[1] * b_val;
    coefs[43] += tri_consts[1] * b_val;
    coefs[46] += tri_consts[0] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[50] -= b_val;
    coefs[51] += b_val;
    coefs[58] += tri_consts[1] * b_val;
    coefs[59] -= tri_consts[1] * b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[38] -= tri_consts[1] * b_val;
    coefs[39] += tri_consts[0] * b_val;
    coefs[42] += tri_consts[3] * b_val;
    coefs[43] -= tri_consts[2] * b_val;
    coefs[46] -= tri_consts[1] * b_val;
    coefs[47] += tri_consts[0] * b_val;
    coefs[54] += tri_consts[1] * b_val;
    coefs[55] -= tri_consts[0] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[2] * b_val;
    coefs[62] += tri_consts[1] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[38] += b_val;
    coefs[39] -= b_val;
    coefs[42] -= tri_consts[0] * b_val;
    coefs[43] += tri_consts[0] * b_val;
    coefs[46] += b_val;
    coefs[47] -= b_val;
    coefs[54] -= b_val;
    coefs[55] += b_val;
    coefs[58] += tri_consts[0] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[62] -= b_val;
    coefs[63] += b_val;
    ii =  8 * ( (ix  ) + nx * ( (iy+1) + ny * (iz+1) ) );
    b_val = LUT[ii];
    coefs[40] += tri_consts[5] * b_val;
    coefs[42] -= tri_consts[8] * b_val;
    coefs[43] += tri_consts[7] * b_val;
    coefs[44] -= tri_consts[3] * b_val;
    coefs[46] += tri_consts[7] * b_val;
    coefs[47] -= tri_consts[6] * b_val;
    coefs[56] -= tri_consts[3] * b_val;
    coefs[58] += tri_consts[7] * b_val;
    coefs[59] -= tri_consts[6] * b_val;
    coefs[60] += tri_consts[2] * b_val;
    coefs[62] -= tri_consts[6] * b_val;
    coefs[63] += tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[41] += tri_consts[5] * b_val;
    coefs[42] -= tri_consts[7] * b_val;
    coefs[43] += tri_consts[5] * b_val;
    coefs[45] -= tri_consts[3] * b_val;
    coefs[46] += tri_consts[6] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[57] -= tri_consts[3] * b_val;
    coefs[58] += tri_consts[6] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[61] += tri_consts[2] * b_val;
    coefs[62] -= tri_consts[4] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[40] -= tri_consts[1] * b_val;
    coefs[42] += tri_consts[5] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[44] += tri_consts[1] * b_val;
    coefs[46] -= tri_consts[5] * b_val;
    coefs[47] += tri_consts[3] * b_val;
    coefs[56] += tri_consts[0] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[2] * b_val;
    coefs[60] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[40] -= tri_consts[1] * b_val;
    coefs[42] += tri_consts[5] * b_val;
    coefs[43] -= tri_consts[3] * b_val;
    coefs[44] += tri_consts[0] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[2] * b_val;
    coefs[56] += tri_consts[1] * b_val;
    coefs[58] -= tri_consts[5] * b_val;
    coefs[59] += tri_consts[3] * b_val;
    coefs[60] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[3] * b_val;
    coefs[63] -= tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[41] -= tri_consts[1] * b_val;
    coefs[42] += tri_consts[3] * b_val;
    coefs[43] -= tri_consts[1] * b_val;
    coefs[45] += tri_consts[1] * b_val;
    coefs[46] -= tri_consts[3] * b_val;
    coefs[47] += tri_consts[1] * b_val;
    coefs[57] += tri_consts[0] * b_val;
    coefs[58] -= tri_consts[2] * b_val;
    coefs[59] += tri_consts[0] * b_val;
    coefs[61] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[2] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[41] -= tri_consts[1] * b_val;
    coefs[42] += tri_consts[3] * b_val;
    coefs[43] -= tri_consts[1] * b_val;
    coefs[45] += tri_consts[0] * b_val;
    coefs[46] -= tri_consts[2] * b_val;
    coefs[47] += tri_consts[0] * b_val;
    coefs[57] += tri_consts[1] * b_val;
    coefs[58] -= tri_consts[3] * b_val;
    coefs[59] += tri_consts[1] * b_val;
    coefs[61] -= tri_consts[0] * b_val;
    coefs[62] += tri_consts[2] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[40] += b_val;
    coefs[42] -= tri_consts[1] * b_val;
    coefs[43] += tri_consts[0] * b_val;
    coefs[44] -= b_val;
    coefs[46] += tri_consts[1] * b_val;
    coefs[47] -= tri_consts[0] * b_val;
    coefs[56] -= b_val;
    coefs[58] += tri_consts[1] * b_val;
    coefs[59] -= tri_consts[0] * b_val;
    coefs[60] += b_val;
    coefs[62] -= tri_consts[1] * b_val;
    coefs[63] += tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[41] += b_val;
    coefs[42] -= tri_consts[0] * b_val;
    coefs[43] += b_val;
    coefs[45] -= b_val;
    coefs[46] += tri_consts[0] * b_val;
    coefs[47] -= b_val;
    coefs[57] -= b_val;
    coefs[58] += tri_consts[0] * b_val;
    coefs[59] -= b_val;
    coefs[61] += b_val;
    coefs[62] -= tri_consts[0] * b_val;
    coefs[63] += b_val;
    ii =  8 * ( (ix+1) + nx * ( (iy+1) + ny * (iz+1) ) );
    b_val = LUT[ii];
    coefs[42] += tri_consts[8] * b_val;
    coefs[43] -= tri_consts[7] * b_val;
    coefs[46] -= tri_consts[7] * b_val;
    coefs[47] += tri_consts[6] * b_val;
    coefs[58] -= tri_consts[7] * b_val;
    coefs[59] += tri_consts[6] * b_val;
    coefs[62] += tri_consts[6] * b_val;
    coefs[63] -= tri_consts[4] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[42] -= tri_consts[5] * b_val;
    coefs[43] += tri_consts[5] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[62] -= tri_consts[2] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[42] -= tri_consts[5] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[46] += tri_consts[5] * b_val;
    coefs[47] -= tri_consts[3] * b_val;
    coefs[58] += tri_consts[3] * b_val;
    coefs[59] -= tri_consts[2] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[42] -= tri_consts[5] * b_val;
    coefs[43] += tri_consts[3] * b_val;
    coefs[46] += tri_consts[3] * b_val;
    coefs[47] -= tri_consts[2] * b_val;
    coefs[58] += tri_consts[5] * b_val;
    coefs[59] -= tri_consts[3] * b_val;
    coefs[62] -= tri_consts[3] * b_val;
    coefs[63] += tri_consts[2] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[42] += tri_consts[1] * b_val;
    coefs[43] -= tri_consts[1] * b_val;
    coefs[46] -= tri_consts[1] * b_val;
    coefs[47] += tri_consts[1] * b_val;
    coefs[58] -= tri_consts[0] * b_val;
    coefs[59] += tri_consts[0] * b_val;
    coefs[62] += tri_consts[0] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[42] += tri_consts[1] * b_val;
    coefs[43] -= tri_consts[1] * b_val;
    coefs[46] -= tri_consts[0] * b_val;
    coefs[47] += tri_consts[0] * b_val;
    coefs[58] -= tri_consts[1] * b_val;
    coefs[59] += tri_consts[1] * b_val;
    coefs[62] += tri_consts[0] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[42] += tri_consts[1] * b_val;
    coefs[43] -= tri_consts[0] * b_val;
    coefs[46] -= tri_consts[1] * b_val;
    coefs[47] += tri_consts[0] * b_val;
    coefs[58] -= tri_consts[1] * b_val;
    coefs[59] += tri_consts[0] * b_val;
    coefs[62] += tri_consts[1] * b_val;
    coefs[63] -= tri_consts[0] * b_val;
    ii++;
    b_val = LUT[ii];
    coefs[42] -= b_val;
    coefs[43] += b_val;
    coefs[46] += b_val;
    coefs[47] -= b_val;
    coefs[58] += b_val;
    coefs[59] -= b_val;
    coefs[62] -= b_val;
    coefs[63] += b_val;

    return;
}


#if !defined( _GPUCODE ) && defined( __cplusplus )
}
#endif /* !defined( _GPUCODE ) && defined( __cplusplus ) */

#endif /* SIXTRACKLIB_COMMON_BE_TRICUB_COEFFICIENTS_C99_H__ */


